from app.schemas.user import UserBase, UserCreate, UserUpdate, UserSchema, Token, TokenData, LoginRequest
from app.schemas.contacto import ContactoBase, ContactoCreate, ContactoUpdate, ContactoSchema
from app.schemas.fabricante import FabricanteBase, FabricanteCreate, FabricanteUpdate, FabricanteSchema
from app.schemas.producto import ProductoBase, ProductoCreate, ProductoUpdate, ProductoSchema
from app.schemas.actividad import ActividadBase, ActividadCreate, ActividadUpdate, ActividadSchema, PaginatedActividades
from app.schemas.nota import NotaBase, NotaCreate, NotaSchema
from app.schemas.oportunidad import (
    OportunidadProductoBase,
    OportunidadProductoCreate,
    OportunidadProductoSchema,
    OportunidadBase,
    OportunidadCreate,
    OportunidadUpdate,
    OportunidadEtapaUpdate,
    OportunidadSchema,
    OportunidadDetail,
    PaginatedOportunidades,
)
from app.schemas.cliente import (
    ClienteBase,
    ClienteCreate,
    ClienteUpdate,
    ClienteSchema,
    ClienteDetailSchema,
    ClienteStatsSchema,
    PaginatedClientes,
)
from app.schemas.dashboard import (
    DashboardSummary,
    PipelinePorEtapa,
    PipelinePorVendedor,
    PipelinePorFabricante,
    ForecastResponse,
    WinLossTrendItem,
)

__all__ = [
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserSchema",
    "Token",
    "TokenData",
    "LoginRequest",
    "ContactoBase",
    "ContactoCreate",
    "ContactoUpdate",
    "ContactoSchema",
    "FabricanteBase",
    "FabricanteCreate",
    "FabricanteUpdate",
    "FabricanteSchema",
    "ProductoBase",
    "ProductoCreate",
    "ProductoUpdate",
    "ProductoSchema",
    "ActividadBase",
    "ActividadCreate",
    "ActividadUpdate",
    "ActividadSchema",
    "PaginatedActividades",
    "NotaBase",
    "NotaCreate",
    "NotaSchema",
    "OportunidadProductoBase",
    "OportunidadProductoCreate",
    "OportunidadProductoSchema",
    "OportunidadBase",
    "OportunidadCreate",
    "OportunidadUpdate",
    "OportunidadEtapaUpdate",
    "OportunidadSchema",
    "OportunidadDetail",
    "PaginatedOportunidades",
    "ClienteBase",
    "ClienteCreate",
    "ClienteUpdate",
    "ClienteSchema",
    "ClienteDetailSchema",
    "ClienteStatsSchema",
    "PaginatedClientes",
    "DashboardSummary",
    "PipelinePorEtapa",
    "PipelinePorVendedor",
    "PipelinePorFabricante",
    "ForecastResponse",
    "WinLossTrendItem",
]
